org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13

minecraft_version=1.21.1

jei_version=19.21.0.247
mod_version=1.21.1-3.0.4

minecraft_version_range=[1.21,1.21.3)
neo_version=21.1.215
neo_version_range=[21.1.128,)
loader_version_range=[4,)

flywheel_version = 1.0.1-11

mod_id=thirst
mod_name=Thirst Was Reclaimed
mod_license=MIT
mod_group_id=cn.mlus.thirst
mod_authors=mlus
mod_description=Brand-new take on the thirst-bar mechanic, compatible with a lot of contemporary mods
